AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation will create an EC2 instance and deploy the useful API in US-EAST-1. AWS beanstalk can be used as a quick alternative.'
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t3.nano, t3.micro]
    ConstraintDescription: must be a valid EC2 instance type.
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: 
        - !Ref InstanceSecurityGroup
      ImageId: ami-0fc61db8544a617ed
      UserData:
        Fn::Base64: 
          #Debug with /var/log/cloud-init-output.log
          !Sub |
            #!/bin/bash -xe
            yum update -y
            yum install git -y
            git clone https://github.com/tomand285/usefulAPI.git
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install node
            cd usefulAPI
            npm install
            npm start
      Tags:
        - Key: Name
          Value: Useful API
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable tcp access via port 3000
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIpv6: "::/0"
  InstanceLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
      - "us-east-1b"
      Instances:
      - !Ref EC2Instance
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '3000'
        Protocol: HTTP
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  PublicIP:
    Description: Public IP address of the newly created EC2 instance, use port 3000
    Value: !GetAtt [EC2Instance, PublicIp]
  ELB:
    Description: Public DNSName of the newly created ELB to the EC2 instance
    Value: !GetAtt [InstanceLoadBalancer, DNSName]